config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from manager.views import ImageListView, CreateUploadView, DeleteUploadView

app_name = 'manager'

urlpatterns = [
    path('', ImageListView.as_view(), name="list_image"),
    path('upload/', CreateUploadView.as_view(), name="upload"),
    path('delete/<int:pk>', DeleteUploadView.as_view(), name="delete"),
]

manager/models.py
import uuid
import os
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from .utils import upload_image_path

class UploadManager(models.Model):
	"""
		Represents a uploader image file
	"""

	title = models.CharField(verbose_name='title image', max_length=128, blank=True)

	image = models.ImageField(verbose_name='image', upload_to=upload_image_path)
	thumbnail = ImageSpecField(
		source='image',
		processors=[ResizeToFill(530, 470)],
		options={'quality': 1000},
	)

	image_width = models.CharField(verbose_name='image width', max_length=16, default='0', blank=True)
	image_height = models.CharField(verbose_name='image height', max_length=16, default='0', blank=True)
	type_image = models.CharField(verbose_name='type image', max_length=12, default='jpg', blank=True)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title


@receiver(pre_delete, sender=UploadManager)
def pre_delete_image(sender, instance, **kwargs):
	object_current = sender.objects.get(pk=instance.pk)

	if object_current:
		os.remove(object_current.image.path)
		os.remove(object_current.thumbnail.path)
		r = os.path.dirname(object_current.thumbnail.path)
		os.rmdir(r)

manager/forms.py
from django import forms
from django.core.exceptions import ValidationError
from upload_validator import FileTypeValidator

from .models import UploadManager


class UploadManagerForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	image = forms.FileField(
		label='', help_text="Formats accepted: JPEG nd PNG nd JPG nd GIF",
		validators=[FileTypeValidator(
			allowed_types=[ 'image/jpeg','image/jpg', 'image/png', 'image/gif']
		)]
	)

	class Meta:
		model = UploadManager
		fields = ('image', 'title')
	
	def clean_image(self):
		image = self.cleaned_data.get('image')
		print(image.size)
		fileSize = image.size
		megabyte_limit = 3.0

		if fileSize > megabyte_limit * 1024 * 1024:
			raise ValidationError("Max file size is %sMB" % str(megabyte_limit))

		return image

manager/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from PIL import Image
from .models import UploadManager
from .forms import UploadManagerForm


class ImageListView(ListView):
    model = UploadManager
    template_name = 'manager/image_list.html'
    paginate_by = 20


class CreateUploadView(CreateView):
    # model = UploadManager
    form_class = UploadManagerForm
    template_name = 'manager/upload.html'
    success_url = reverse_lazy('manager:list_image')

    def form_valid(self, form):
        response = form.save(commit=False)
        
        context = {
            'form': form
        }

        if form.is_valid():
            image = form.cleaned_data.get('image')
            title = form.cleaned_data.get('title')
            if title is None or title == '':
                title = image.name
            
            infoImage = Image.open(image)
            width, height = infoImage.size

            uplader = UploadManager.objects.create(
                title=title,
                image=image,
                image_width=width,
                image_height=height,
                type_image=infoImage.format
            )
            if uplader:
                return redirect('manager:upload')
        
        return render(self.request, self.template_name, context)

    def get(self, request, *args, **kwargs):
        form = self.form_class
        context = { 'form': form }
        return render(request, self.template_name, context)


class DeleteUploadView(DeleteView):
    model = UploadManager
    success_url = reverse_lazy('manager:list_image')

manager/templates/manager/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'manager/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'manager/css/styles.css' %}">
    {% block ref_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainNavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'manager:list_image' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:upload' %}">Upload image</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:list_image' %}">List image</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="{% static 'manager/js/jquery.js' %}"></script>
    <script src="{% static 'manager/js/bootstrap.bundle.min.js' %}"></script>
    {% block ref_js %}{% endblock %}
</body>
</html>

manager/templates/manager/image_list.html
{% extends 'manager/base.html' %}

{% block title %}List Image{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h3 class="text-capitalize mt-3">List image</h3>
            <hr>
            <div class="row row-cols-1 row-cols-md-5">
               
                {% for object in object_list %}
                    <div class="col mb-4 mt-4">
                     
                        <div class="card">
                            <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="{{ object.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.title }}</h5>
                                <div class="btn-group-vertical">
                                    <a href="{{ object.image.url }}" target="_blank" class="btn btn-danger btn-block">Original Image</a>
                                    <a href="{{ object.thumbnail.url }}" target="_blank" class="btn btn-primary btn-block">Thumbnail Image</a>
                                </div>
                                <p>
                                    Image size:
                                    <span>{{ object.image_width }} * {{ object.image_height }}</span>
                                </p>
                                <p>
                                    Image type:
                                    {{ object.type_image }}
                                </p>
                                <p>
                                    Created at:
                                    {{ object.created_at|date:"d-m-Y" }}
                                </p>
                                <a href="{% url 'manager:delete' object.pk %}" class="btn btn-warning btn-block">Delete</a>
                            </div>
                    </div>
                </div>
                {% endfor %}
                
            </div>
        </div>

        <div class="row">
            <nav aria-label="Page navigation example">
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                    {% endif %}

                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                    {% endif %}
                </ul>
            {% endif %}
            </nav>
        </div>
    </div>
{% endblock %}

manager/templates/manager/upload.html
{% extends 'manager/base.html' %}

{% block title %}List Image{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-9 mt-5">
                <h3>Upload image</h3>
                <hr>
                <div class="card">
                    <div class="card-body">
                        <div class="alert alert-info">
                            Formats accept (JPG, JPEG, PNG, GIF)
                        </div>
                        <div class="alert alert-warning">
                            Max file size is 3.0MB
                        </div>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="{{ form.title.id_for_label }}">title: </label>
                                {{ form.title }}
                                {{ form.title.errors }}
                            </div>

                            <div class="form-group">
                                <label for="{{ form.image.id_for_label }}">Image: </label>
                                {{ form.image }}
                                {{ form.image.errors }}
                            </div>

                            <button type="submit" class="btn btn-outline-primary">Upload</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

manager/templates/manager/uploadmanager_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>